### ISSUE TITLE
Upload image on Firebase

### ISSUE THREAD

**Issue by JEricaM** [peterpeterparker/ionic-pwa-camera-no-plugins#1]
Hi
First of all thank you for this code, it's amazing! 

Is it possible to uload the image to firebase hosting? I'm trying to do it in my code but I try to upload **imgURI**, the console gives me an error about the format of the image. 

`core.js:15724 ERROR Error: Uncaught (in promise): FirebaseStorageError: {"code_":"storage/invalid-format","message_":"Firebase Storage: String does not match format 'base64': Invalid character found","serverResponse_":null,"name_":"FirebaseError"}`

I don't understand how to solve this because I always uploaded images with the camera plugin and I think that maybe there is a different approach to adopt here.

Thank you in advance.

**Comment by peterpeterparker** [comment]
Hi @JEricaM 

Thx for the feedback. Probably yes you could upload it to Firebase but I never did that, so I won't be able to help exactly

But as far as I understand the message you've got an error because you didn't provide the image content as base64 rather something else. Maybe you could it a try transforming the file into base64.

If that could help, here's a method I use to transform File into Base64: https://github.com/fluster/fluster-app/blob/03e9d3941b73810d01af6a330482bc179ec65187/src/app/services/core/utils/utils.ts#L114

Good luck!

**Comment by JEricaM** [comment]
Hi, thank you for the response.

I've used your method to transform File into Base 64, because I'm using the code of your home.ts but the problem still happens unfortunately.

**Comment by peterpeterparker** [comment]
Maybe https://stackoverflow.com/questions/41299288/firebase-storage-string-does-not-match-format-base64-invalid-character-found ?

**Comment by peterpeterparker** [comment]
Awesome and good to know 👍
